version: '3.8'

services:
  # Our Python web application (like an EC2 instance)
  my-app:
    build: ./app
    container_name: my-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  # Our Monitoring Service (like CloudWatch Metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Our Visualization Service (like CloudWatch Dashboards), now fully automated!
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      # This line mounts our local provisioning files into the container
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      # This allows anonymous access, so you don't need to log in for the demo
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin